Available trackers:
Tracker
TrackerDaSiamRPN
TrackerDaSiamRPN_Params
TrackerDaSiamRPN_create
TrackerGOTURN
TrackerGOTURN_Params
TrackerGOTURN_create
TrackerMIL
TrackerMIL_Params
TrackerMIL_create
TrackerNano
TrackerNano_Params
TrackerNano_create
